---
title: "Course Notes 17"
description: |
  Ruling out closed orbits. 
author:
  - name: Jason M. Graham 
    url: https://topicsinbiomath.netlify.app/
    affiliation: University of Scranton 
    affiliation_url: https://sites.google.com/site/jasonmgrahamus/
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
creative_commons: CC BY-NC
bibliography: topics_in_biomath.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(deSolve)
library(tidyverse)
library(ggformula)
library(patchwork)
library(phaseR)
library(latex2exp)
library(DiagrammeR)
theme_set(theme_light())
```


# Goals

After reading this section of notes, you should

1) know what a gradient system is and understand why such a system can not have a closed orbit, 

2) know what a Liapunov function is, and

3) know Dulac's criterion and how to apply it. 

# Background

From our experiences so far, we know that a two-dimensional autonomous system of the form

$$
\begin{align}
\frac{dx}{dt} &= f(x,y) \\
\frac{dy}{dt} &= g(x,y)
\end{align}
$$
may possess closed orbits either in the form of a nonlinear center or a limit cycle. However, in general, it is tricky to confirm the existence of a closed orbit for a nonlinear system. In this section of notes, we provide some techniques for ruling out the possibility of closed orbits. Here we closely follow section 7.2 from [@strogatzNonlinearDynamicsChaos2015] and recommend it for further reading. 

# Techniques for Ruling Out Closed Orbits


## Gradient systems


## Liapunov functions


## Dulac's criterion





# Summary





# Further Reading 

For further details on the topics covered in this section of notes, see Chapter 7 from [@strogatzNonlinearDynamicsChaos2015]. 

