---
title: "Course Notes 19"
description: |
  An introduction to the Hodgkin-Huxley ODEs. 
author:
  - name: Jason M. Graham 
    url: https://topicsinbiomath.netlify.app/
    affiliation: University of Scranton 
    affiliation_url: https://sites.google.com/site/jasonmgrahamus/
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
creative_commons: CC BY-NC
bibliography: topics_in_biomath.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(deSolve)
library(tidyverse)
library(ggformula)
library(patchwork)
library(phaseR)
library(latex2exp)
library(DiagrammeR)
source("./R/gatingVariables.R")
theme_set(theme_light())
```


# Goals

After reading this section of notes, you should

1) know what is a membrane potential, an action potential, and an ion channel in the context of nerve cells (neurons);

2) have an appreciation for how the classical Hodgkin-Huxley ODEs model essential biophysics of neurons; and

2) be aware of some of the dynamics exhibited by neural systems and how this relates to neural physiology. 

# Background

Nerve cells known as [neurons](https://en.wikipedia.org/wiki/Neuron) can produce electrical impulses. During the 1940s and 1950s scientists conducted and published research results that elucidate the biophysics of nerve cell electrical impulses. This work is remarkable for its synthesis of experiment and theory. In particular, researchers measured electrical output from the [giant axon of a squid](https://en.wikipedia.org/wiki/Squid_giant_axon) and used these measurements as a basis for deriving a mathematical model that captures key features of the so-called [action potential](https://en.wikipedia.org/wiki/Action_potential) of the neuron. 

Noteworthy is the paper [*A quantitative description of membrane current and its application to conduction and excitation in nerve*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1392413/) by [Alan Hodgkin](https://en.wikipedia.org/wiki/Alan_Hodgkin) and [Andrew Huxley](https://en.wikipedia.org/wiki/Andrew_Huxley) which presents equations now known as the [Hodgkin-Huxley model](https://en.wikipedia.org/wiki/Hodgkin%E2%80%93Huxley_model). This paper is one in a series of five papers presenting research for which Hodgkin and Huxley where eventually awarded a [Nobel Prize in Physiology or Medicine](https://en.wikipedia.org/wiki/Nobel_Prize_in_Physiology_or_Medicine). The Hodgkin-Huxley model is foundational for mathematical and [computational neuroscience](https://en.wikipedia.org/wiki/Computational_neuroscience), and the equations have generated a lot of interest in the field of biomathematics due to the interesting dynamics they exhibit. 

In this section of notes, we present the classical Hodgkin-Huxley ODEs and attempt to explain what they model. Additionally, we suggest some other avenues of research in mathematical neuroscience. We proceed by quickly reviewing the biophysical concepts that are most essential in understanding the meaning of the terms in the Hodgkin-Huxley model. 

# A Primer in Neural Biophysics 

Here we follow section 1.1 of [@borgersIntroductionModelingNeuronal2017] in presenting the biophysical background and terminology needed to understand the formulation of the classical Hodgkin-Huxley ODEs.  

Recall from physics that [electric potential](https://en.wikipedia.org/wiki/Electric_potential) is the work required to move a unit of electric charge. Nerve and muscle cells contain and are surrounded by charged particles in the form of ions. This may result in a difference in electric potential between the exterior and interior of a cell that is known as a [membrane potential](https://en.wikipedia.org/wiki/Membrane_potential). Further, nerve and muscle cells are capable of generating brief spikes in the membrane potential creating what is known as an [action potential](https://en.wikipedia.org/wiki/Action_potential).  Thus, physiologists say that nerve and muscle cells are **excitable**. Our goal is to understand and model the mechanisms underlying the electrical activity in nerve cells known as neurons.

[Neurons](https://en.wikipedia.org/wiki/Neuron) are one of the primary cells in the brain. A neuron possesses a cell body known as a [soma](https://en.wikipedia.org/wiki/Soma_(biology)), input branches called [dendrites](https://en.wikipedia.org/wiki/Dendrite), and an output unit known as an [axon](https://en.wikipedia.org/wiki/Axon). Moreover, neurons are filled and surrounded by fluid containing sodium ($\text{Na}^{+}$), potassium ($\text{K}^{+}$), chloride ($\text{Cl}^{-}$), and calcium ($\text{Ca}^{2+}$) ions. The superscripts denote the electric charge of the ion. We will denote the concentration of ion $\text{X}$ by $[\text{X}]_{\text{in}}$ if it is within the cell and $[\text{X}]_{\text{ex}}$ if it is outside the cell.  

It is known that ions can pass through the cell membrane of a neuron through so-called [ion channels](https://en.wikipedia.org/wiki/Ion_channel). These channels are typically ion specific in that a sodium ion channel only lets sodium through, a potassium channel only lets potassium through, and so on. Additionally, there are ion pumps at the neuron cell membrane that actively transport ions in or out of a cell but not necessarily at the same rate. For example, the well-known [sodium-potassium](https://en.wikipedia.org/wiki/Sodium-potassium_pump) pump removes sodium and intakes potassium at a 2 potassium for 3 sodium ratio. The point is that this prevents the occurrence of a perfect balance of ion concentrations inside and outside of a neuron cell membrane.  Thus, we have an explanation for the membrane potential of a neuron. 

Going further, the membrane potential of a neuron can decrease (known as hyperpolarization) creating a so-called inhibitory state, or increase (known as depolarization)  creating a so-called excitatory state.  Researchers have observed experimentally these changes in time of the membrane potential of neurons. See, for example, figures in the paper of [Han et al,](https://academic.oup.com/brain/article/135/9/2613/326668) where one can see a plot of a recording of membrane potential from a neuron in the superior cervical ganglion of a rat.  What is seen is that the voltage corresponding to the membrane potential slowly rises until it reaches a threshold level (known as a firing threshold) then a sudden rapid increase in voltage occurs creating a action potential. When a neuron generates an action potential, one often says that it spikes or fires. This is all based on opening and closing of ion channels and the ion channel activity is incorporated into the Hodgkin-Huxley mathematical we describe next. 


# The Hodgkin-Huxley ODEs

Let $v(t)$ denote the neuron membrane potential at time $t$ measured in units of millivolts (mV). For the purposes of the Hodgkin_Huxley model, time will be measured in units of milliseconds (ms). A principle part of the Hodgkin-Huxley models expresses how $v$ changes over time. We start by assuming that a nerve cell membrane acts as a [capacitor](https://en.wikipedia.org/wiki/Capacitor) so that

$Cv = Q$

where $C$ is the (constant) capacitance and $Q$ is the electric charge across the membrane. Recall that the total current relates to the charge by 

$I_{\text{total}} = \frac{dQ}{dt}$

so that if we differentiate both sides of $Cv=Q$ we obtain

$C\frac{dv}{dt} = I_{\text{total}}$

Based on experiments, Hodgkin adn Huxley determined that the total current $I_{\text{total}}$ arises from a combination of 

* a sodium induced current $I_{\text{Na}}$, 

* a potassium induced current $I_{\text{K}}$, 

* a "leak" current $I_{\text{L}}$ induced by chloride and other ions, and

* an experimentally injected current $I$. 

Thus, 

$C\frac{dv}{dt} = I_{\text{Na}} + I_{\text{K}} + I_{\text{L}} + I$

which is the primary equation for the time rate of chance of the  membrane potential $v$. 

Further, it is assumed that the sodium, potassium, and leak currents all obey [Ohm's law](https://en.wikipedia.org/wiki/Ohm%27s_law) which states that the current is proportional to a difference in voltage leading to equations

$$
\begin{align}
I_{\text{Na}} &= g_{\text{Na}}(v_{\text{Na}} - v) \\
I_{\text{K}} &= g_{\text{K}}(v_{\text{K}} - v) \\
I_{\text{L}} &= g_{\text{L}}(v_{\text{L}} - v) 
\end{align}
$$
where $v_{\text{Na}}$, $v_{\text{K}}$, and $v_{\text{L}}$ are the [reversal potential](https://en.wikipedia.org/wiki/Reversal_potential) values for sodium. potassium, and leak, respectively. The values $g_{\text{Na}}$, $g_{\text{K}}$, and $g_{\text{L}}$ are the [conductances](https://en.wikipedia.org/wiki/Electrical_resistance_and_conductance). Thus, we have that

$C\frac{dv}{dt} = g_{\text{Na}}(v_{\text{Na}} - v) + g_{\text{K}}(v_{\text{K}} - v) + g_{\text{L}}(v_{\text{L}} - v) + I$

This appears to be a fairly simple equation. However, it has been determined that while that leak conductance $g_{\text{L}}=\bar{g}_{\text{L}}$ with $\bar{g}_{\text{L}}$ a constant, in contrast, the sodium and potassium conductances change in time in concert with the membrane potential $v$. Thus, it is required to derive equations that relate how the sodium and potassium conductance functions vary. In order to do this, we take in to account the actions of the ion channels discussed previously.

## Gating Variables

From an analysis of experimental results, Hodgkin and Huxley concluded that

$$
\begin{align}
g_{\text{Na}}(t) &= \bar{g}_{\text{Na}} m(t)^3 h(t) \\
g_{\text{K}}(t) &= \bar{g}_{\text{K}} n(t)^4
\end{align}
$$
where the three **gating variables** $m$, $h$, and $n$ are dimensionless time varying functions that each satisfy a differential equation of the form

$\frac{dx}{dt} = \frac{x_{\infty}(v) - x}{\tau_{x}(v)}$

where $x_{\infty}(v)$ and $\tau_{x}(v)$ are functional forms depending on the membrane potential.

Thus, the Hodgkin-Huxley model is

$$
\begin{align}
C\frac{dv}{dt} &= \bar{g}_{\text{Na}}m^3 h (v_{\text{Na}} - v) + \bar{g}_{\text{K}}n^4(v_{\text{K}} - v) + \bar{g}_{\text{L}}(v_{\text{L}} - v) + I \\
\frac{dm}{dt} &= \frac{m_{\infty}(v) - m}{\tau_{m}(v)} \\
\frac{dh}{dt} &= \frac{h_{\infty}(v) - h}{\tau_{h}(v)} \\
\frac{dn}{dt} &= \frac{n_{\infty}(v) - n}{\tau_{n}(v)} 
\end{align}
$$

which is a coupled system of nonlinear equations. We still need to describe the functional forms $m_{\infty}(v)$, $\tau_{m}(v)$; $h_{\infty}(v)$, $\tau_{h}(v)$; and $n_{\infty}(v)$, $\tau_{n}(v)$, but first we consider what is the biophysical interpretation of the gating variables $m$, $h$, and $n$.  

## Interpretation of Gating Variables. 

A sodium channel has four gates aligned in series such that three of the gates are of one type (say type m), and one of the gates is of a second type (say type h). If $m$ is the fraction of open m-gates and $h$ is the fraction of open h-gates, then the fraction of open sodium channels is $m^3h$. Similarly, we assume that potassium has four gates aligned in series all of the same type, type n. Then the fraction of open potassium channels is $n^4$.      

# Further Reading




