---
title: "Fibonacci's Rabbits"
description: |
  The Fibonacci sequence results from an age-structured population model.
author:
  - name: Jason M. Graham
    url: {}
date: 2022-03-30
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

# Background

The sequence of numbers

$$
\begin{array}{ccccccc} x_{0} & x_{1} & x_{2} & x_{3} & \cdots & x_{j} & \cdots \\
0 & 1 & 1 & 2 & \cdots & x_{j-1}+x_{j-2} & \cdots \end{array}
$$
is often called the [Fibonacci numbers](https://en.wikipedia.org/wiki/Fibonacci_number) and is generated by the recurrence relation

$$
x_{n+2} = x_{n+1} + x_{n}, \ \ n=0,1,2,\ldots 
$$
In the book [*A Short History of Mathematical Population Dynamics*](https://link-springer-com.ezp.scranton.edu/book/10.1007/978-0-85729-115-8), the author Bacaër explains how Leonardo of Pisa aka [Fibonacci](https://en.wikipedia.org/wiki/Fibonacci) arrived at this sequence starting from a problem of population dynamics stated in his book [Liber abaci](https://en.wikipedia.org/wiki/Liber_Abaci). A translation of Fibonacci's problem is, quoting from Bacaër:

> A certain man had one pair of rabbits together in a certain enclosed place. One wishes to
know how many are created from the pair in one year when it is the nature of them in a
single month to bear another pair and in the second month those born to bear also.

An analysis of this problems leads to the difference equation $x_{n+2} = x_{n+1} + x_{n}$ which generates the Fibonacci numbers whenever the starting values $x_{0}$ and $x_{1}$ are 0 and 1 respectively. From the statement of Fibonacci's problem, it is apparent that an [age-structured](https://topicsinbiomath.netlify.app/notes014.html#application-age-structured-models) model is appropriate. We elaborate on this in this post. 

# A Model for Fibonacci's Rabbits

An important assumption made in the statement of Fibonacci's rabbit problem is that rabbits are not fertile until they are at least **two months old**. So, if we have a new-born pair of rabbits, they will not give birth until the third month after they are born. Thus, if we let $x_{n}$ be the number of rabbits at the beginning of month $n$, and we assume as stated that each pair of fertile rabbits produces a pair of new-born rabbits and no rabbits die, then the number $x_{n+1}$ of pairs of rabbits at the beginning of the next month is

$x_{n+1} = x_{n} + x_{n-1}$

which is equivalent to the recurrence stated above. There are several ways, one of which is given as a homework assignment in *Topics in Biomathematics*, to show that 

$x_{n} = \frac{1}{\sqrt{5}}\left( \frac{1+\sqrt{5}}{2}\right)^{n} - \frac{1}{\sqrt{5}}\left(\frac{1-\sqrt{5}}{2} \right)^n$

satisfies the Fibonacci recurrence. It is well known that 

$$
\frac{x_{n+1}}{x_{n}} \rightarrow \frac{1+\sqrt{5}}{2}
$$

as $n\rightarrow \infty$, the number $\frac{1+\sqrt{5}}{2}$ is often called the [golden ratio](https://en.wikipedia.org/wiki/Golden_ratio) and it appears in many mathematical and natural patterns. 
